# Generated by Django 3.2.20 on 2024-06-12 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_post_profile_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Profile_img',
            new_name='profile_img',
        ),
    ]
