# Generated by Django 3.2.20 on 2024-06-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_profile_img_post_profile_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
