# Generated by Django 3.2.20 on 2024-06-13 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240612_1528'),
    ]

    operations = [
        migrations.CreateModel(
            name='Followerscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=200)),
            ],
        ),
    ]
