# Generated by Django 3.2.20 on 2024-06-13 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_profile_header_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profile_img',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.profile'),
            preserve_default=False,
        ),
    ]
