# Generated by Django 3.2.20 on 2024-06-13 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='receiver',
            field=models.CharField(max_length=100),
        ),
    ]
